.changeset/tame-spiders-sneeze.md
packages/root/src/render/render.tsx
packages/root/test/fixtures/i18n-url-format/routes/foo/[slug].tsx
packages/root/test/i18n-url-format.test.ts

This PR is related to #107. 
This will allow routes that only have a subset of locales to be able to return `{notFound: true}` within `getStaticProps()` if the route should not exist for a given locale.

fix: inject locale into route params

---

.changeset/bright-geese-drum.md
packages/rds/package.json
packages/rds/src/components/Heading/Heading.tsx
packages/rds/src/components/Text/Text.module.scss
packages/rds/src/components/Text/Text.tsx
packages/rds/src/styles/type.scss
packages/rds/src/utils/classes.ts
packages/rds/tsconfig.json
pnpm-lock.yaml

These two foundational typography components will be the first two components for the Root.js Design System (RDS) and will demonstrate how a project will generally depend on the RDS package and use it within their projects.
The `<Text>` component is a server-rendered component that applies typography styles to an element. The `<Heading>` component is a lightweight wrapper around the <Text> component that specifically outputs `<h1>`, `<h2>`, etc. semantic tags.
The typography styles should be configurable through design tokens using a SCSS map to store configuration values, which may include type sizes (font-size, line-height, letter-spacing), weights (font-weight), transforms (uppercase), family (font-family), and responsive styles based on breakpoints.
These typography components should …

feat: add rds package with <Text> and <Heading>

---

packages/rds/src/styles/base.scss
packages/rds/src/styles/default.scss

Build plan doc with previous discussion/comments:
https://docs.google.com/document/d/1tA5A04pH7asOHjdQZo_1t2g55fOlfNZWvL5p5eVdfHw/edit
The base.scss file is meant to act similarly to a "reset stylesheet" to provide consistency across all components. For the most part, only styles that are useful for ALL projects should be included in this sheet. Advanced options (like smooth-scroll and prefers-reduced-motion animation timing resets) can be disabled via SCSS configuration variables.

feat: base.scss styles for rds

---

.changeset/wicked-kiwis-marry.md
packages/root-cms/core/client.ts
packages/root/src/core/types.ts
packages/root/src/render/render.tsx
packages/root/src/render/router.ts

This is a fix for SSG-built sites running on Root CMS, which requires the rootConfig to be passed to the RootCMSClient.
```typescript
export async function getStaticPaths(ctx) {
const client = new RootCMSClient(ctx.rootConfig);
const docs = await client.listDocs(...);
return {paths: ...};
}
```

feat: pass rootConfig as context to getStaticPaths

---

.changeset/tiny-dancers-shake.md
examples/blog/collections/BlogPosts.schema.ts
examples/blog/templates/TemplateHero/TemplateHero.schema.ts
packages/root-cms/cli/commands/generate-types.ts
packages/root-cms/ui/components/DocEditor/DocEditor.tsx
packages/root-cms/ui/components/NewDocModal/NewDocModal.tsx
packages/root-cms/ui/hooks/useDraft.ts
packages/root-cms/ui/utils/array-map.ts
packages/root-cms/ui/utils/fields.ts

With this change, selecting a new type in the `oneOf` field will initially default to a default value. When a user switches back to a previous type, the previous value for that type will be automatically re-inserted.

feat: add default value caching for object fields

---

.changeset/cold-rivers-flash.md
packages/root-cms/cli/init-firebase.ts
packages/root-cms/core/client.ts
packages/root-cms/core/plugin.ts
packages/root-cms/core/runtime.ts
packages/root-cms/core/versions.ts
packages/root-cms/ui/ui.tsx

Context: Root CMS requires firestore to be in "native" mode. Some older GCP projects will have the default database in "datastore" mode, which cannot be easily migrated. Those projects can create a "new database" in native mode and they can set which database to use by updating the root.config.ts file:
```typescript
firebaseConfig: {
...
databaseId: 'my-native-firestore-database-id',
}
```

feat: add support for non-default firestore databases

---

.changeset/flat-gifts-battle.md
docs/blocks/ImageBlock/ImageBlock.schema.ts
docs/root-cms.d.ts
packages/root-cms/core/schema.ts
packages/root-cms/ui/components/DocEditor/DocEditor.css
packages/root-cms/ui/components/DocEditor/DocEditor.tsx

The "inline" drawer option to object fields allows users to create "expandable" fields that are hidden away, useful for adding "advanced" features without cluttering the UI.
fixes #287

feat: add "inline" option to object drawers

---

.changeset/calm-hotels-carry.md
packages/root-cms/ui/components/DocStatusBadges/DocStatusBadges.tsx

feat: add status badge for locked docs

---

.changeset/quick-mice-sit.md
docs/templates/Divider/Divider.schema.ts
packages/root-cms/ui/components/DocEditor/DocEditor.css
packages/root-cms/ui/components/DocEditor/DocEditor.tsx
packages/root-cms/ui/components/RichTextEditor/RichTextEditor.css
packages/root-cms/ui/pages/DocumentPage/DocumentPage.css

When user hovers over a field label, it should present a `#` symbol which can be used for deeplinking. When the CMS editor loads, it will automatically "open" all parent drawers for the deeplink and scroll to it, highlighting it in yellow.
screens:
fixes #351

feat: add cms field deeplinking

---

.changeset/chilled-lizards-hide.md
packages/root-cms/core/plugin.ts

Note: This bug fixes a case sensitive issue with unauthorized users being able to see the CMS UI by accessing /CMS (all caps). The user would not have been able to see any of the actual content which is guarded by firestore's security rules.
With this fix, there are additional checks to ensure the user is logged in and verified to have access (via the site's ACL) before being rendered the CMS UI.

fix: prevent unauthorized users from accessing cms ui

---

packages/root-cms/ui/pages/CollectionPage/CollectionPage.tsx
packages/root-cms/ui/pages/ProjectPage/ProjectPage.tsx

- empty space appears when collection description is left blank

fix: remove empty space below collection name

---

.changeset/perfect-phones-cheer.md
packages/root-cms/ui/components/DocEditor/DocEditor.tsx

- enables quick copying and pasting before/after via the menu
screencast:
https://github.com/user-attachments/assets/edad294c-b5f0-4ec6-bace-4e642718e970
#437

feat: add preliminary virtual clipboard to arrays

---

.changeset/funny-apples-hide.md
packages/root-cms/ui/components/DocEditor/DocEditor.css
packages/root-cms/ui/components/DocEditor/DocEditor.tsx

screencast:
https://github.com/user-attachments/assets/026412b9-6ef3-4a21-abd1-367a99f3ac0a
- the focus ring is only visible once you use the hotkeys
- otherwise, the only ui change is the last-moved field gets underlined (this helps disambiguate between two fields with the same preview)

feat: add hotkey support to array items in doc editor

---

packages/root/src/render/render.tsx

I ran into a consistency issue with a project where the `index.tsx` and `[[...page]].tsx` both generated files for the same route, so it became inconsistent across builds.
In Amagaki, this was a build failure. Not sure we should make this a bonafide failure so for now I've made it emit a warning (that will at least assist with debugging).

chore: add warning when multiple routes generate the same path

---

packages/root-cms/ui/components/EditTranslationsModal/EditTranslationsModal.css

this is a small change to make it easier to see the source string when working with large numbers of long translation strings

chore: stick translations fields to top

---

.changeset/khaki-otters-ring.md
packages/root-cms/core/app.tsx
packages/root-cms/core/schema.ts
packages/root-cms/ui/components/DocEditor/DocEditor.tsx

The "id" is the identifier used to store in the DB. The collection "name" is a user-friendly label that's rendered in the CMS UI.

fix: add id to serialized collection data

---

packages/root-cms/ui/components/DocEditor/DocEditor.tsx
packages/root-cms/ui/components/DocEditor/fields/SelectField.tsx

this helps with long lists of values; the user can hit the first letter of the template to jump to it

chore: make select fields searchable

---

packages/root/src/render/route-trie.test.ts

- update the route trie test label to use "parameterized"
- `pnpm test` *(fails: could not fetch pnpm due to network restrictions)*

chore: fix test label typo

---

packages/root/src/render/route-trie.test.ts

- verify that RouteTrie.walk visits every registered route exactly once
- `node` (no tests available)

chore: add walk test for RouteTrie

---

examples/basepath/root.config.ts
examples/starter/root.config.ts

- fix `rootDir` declarations in example configs
- `pnpm test` *(fails: Connect Timeout Error)*

Remove extra semicolons in example configs

---

packages/root-cms/ui/pages/DataSourcePage/DataSourcePage.tsx
packages/root-cms/ui/pages/ReleasePage/ReleasePage.tsx
packages/root-cms/ui/pages/TranslationsArbPage/TranslationsArbPage.tsx

- add row key when rendering DataSourcePage table
- give ReleasePage doc list items unique keys
- key ARB preview rows by source value
- `pnpm test` *(fails: ConnectTimeoutError when fetching pnpm)*

Fix missing keys for mapped elements

---

packages/root-cms/ui/components/DocEditor/DocEditor.tsx

- use `useCallback` for DocEditor navigation helpers
- remove unused root ref and add missing effect deps
- `pnpm lint` *(fails: Error when performing the request to https://registry.npmjs.org/pnpm/-/pnpm-8.9.0.tgz)*

Improve DocEditor hooks

---

.changeset/afraid-meals-smash.md
.gitignore
packages/root-cms/core/client.ts
packages/root-cms/core/core.ts
packages/root-cms/core/plugin.ts
packages/root-cms/core/translations-manager.ts
packages/root-cms/package.json
packages/root-cms/shared/strings.ts
pnpm-lock.yaml

This is the first (of many) `v2` features that are imported into `v1` releases behind experiment flags, which allows developers to test and migrate content before the `v2` version is released.

feat: add TranslationsManager from `v2` branch

---

.changeset/quiet-snakes-leave.md
docs/collections/Pages.schema.ts
packages/root-cms/core/app.tsx
packages/root-cms/core/schema.ts
packages/root-cms/ui/hooks/useDraft.ts

- add `autolock` and `autolockReason` options for collections
- autolock docs when editing in CMS
- include autolock setting in serialized collection info
- demo autolock in `Pages` collection
- add changeset
Fixes #349

Add autolock on edit

---

.changeset/plucky-birds-obey.md
packages/root/src/core/hooks/useStringParams.ts
packages/root/src/core/hooks/useStringParams.tsx
packages/root/test/fixtures/string-params/root.config.ts
packages/root/test/fixtures/string-params/routes/index.tsx
packages/root/test/string-params.test.ts

- merge params from nested `StringParamsProvider`
- test nested provider interaction
- add changeset for `@blinkk/root`
- `pnpm test` *(fails: Error when performing the request to https://registry.npmjs.org/...)*

feat(root): merge nested StringParamsProvider

---

packages/root/src/render/router.ts

- skip `getStaticPaths` when a route has no URL parameters
- `pnpm test` *(fails: Connect Timeout Error)*

Fix SSG static paths for non-parameterized routes

---

.changeset/slimy-snails-change.md
packages/root-cms/ui/components/DocEditor/DocEditor.tsx

- Enable using deeplinks without fully reloading the page
- Make a subtle fix for scrolling _to_ the deeplink
- Change the scroll behavior to "immediate" to remove the delay before focusing the field
@stevenle Mind taking a look? Let me know if you'd like me to _restore_ the smooth scrolling or if you want to leave it as "immediate".
https://github.com/user-attachments/assets/8a08dde7-76dc-4a5b-970b-9eadb92d8963

Polish deeplink behavior

---

packages/root-cms/ui/pages/DocumentPage/DocumentPage.css
packages/root-cms/ui/pages/DocumentPage/DocumentPage.tsx

Until we have more things to add to the menu, I think visually this provides a bit more balance to the UI:

chore: move doc editjson menu into an actionicon

---

packages/root-cms/ui/utils/gcs.ts

- Previously, it would reject if the whole file wasn't uploaded within 10 seconds
- Really, we just wanted to check for stalls, so after _any_ progress is made, we can clear the stall timeout
fixes #650

chore: clear stall timeout after _any_ progress was made

---

package.json
scripts/dev_cms.sh

The command `pnpm cms:dev` will now start a file watcher for the root-cms package, wait 2 seconds, then start the docs Root server.

chore: add script for starting a cms dev server

---

packages/root-cms/ui/components/DocEditor/DocEditor.css

- the basic issue is that when modules are deeply nested it can be difficult to understand "where" in the tree you are
- by adding additional stickiness to nested fields, it makes it a bit easier to understand your position
- for now, i've added the sticky behavior for the first three levels of nested array items
- keep the change a minimal / surgical one in CSS only

chore: enable sticky header for nested array headers

---

.changeset/tall-scissors-flow.md
packages/root-cms/ui/components/DocEditor/DocEditor.tsx
packages/root-cms/ui/hooks/useDeeplink.tsx
packages/root-cms/ui/hooks/useVirtualClipboard.tsx

Prior to this change, any change to a field value will run the extractStrings() method which can be expensive. This change updates the behavior so that extractStrings() is only called when the "show translations" action icon is clicked.
This commit also moves the useDeeplink() hook into its own file.

fix: fix perf issue with translate modal

---

packages/root-cms/ui/hooks/useVirtualClipboard.tsx
packages/root-cms/ui/ui.tsx

The VirtualClipboard was recently updated to use the Clipboard API directly, which no longer requires a provider for handling clipboard state.

chore: remove VirtualClipboardProvider
