.changeset/silver-walls-care.md
packages/root/src/render/render.tsx
packages/root/test/fixtures/i18n-url-format/routes/foo/[slug].tsx

fix: prefix system injected route params with $

---

.changeset/spicy-donuts-cough.md
examples/blog/tsconfig.json
examples/starter/tsconfig.json

feat: add tsconfig options for lit to starter

---

.changeset/brown-peas-grow.md
.changeset/selfish-lizards-juggle.md
examples/blog/root-cms.d.ts
examples/blog/root.config.ts
examples/blog/routes/blog/[blog-post].tsx
examples/blog/routes/index.tsx
examples/blog/templates/TemplateFeaturedBlogPosts/TemplateFeaturedBlogPosts.schema.ts
examples/blog/templates/TemplateFeaturedBlogPosts/TemplateFeaturedBlogPosts.tsx
packages/root-cms/core/api.ts
packages/root-cms/core/app.tsx
packages/root-cms/core/csv.ts
packages/root-cms/core/plugin.ts
packages/root-cms/core/schema.ts
packages/root-cms/package.json
packages/root-cms/signin/signin.tsx
packages/root-cms/signin/styles/signin.css
packages/root-cms/ui/components/DocEditor/DocEditor.css
packages/root-cms/ui/components/DocEditor/DocEditor.tsx
packages/root-cms/ui/components/Heading/Heading.css
packages/root-cms/ui/components/Heading/Heading.tsx
packages/root-cms/ui/components/LocalizationModal/LocalizationModal.css
packages/root-cms/ui/components/LocalizationModal/LocalizationModal.tsx
packages/root-cms/ui/hooks/useDraft.ts
packages/root-cms/ui/ui.tsx
packages/root/src/core/config.ts
packages/root/src/core/types.ts
packages/root/src/render/render.tsx
packages/root/test/fixtures/i18n-url-format/routes/index.tsx
packages/root/test/i18n-url-format.test.ts
pnpm-lock.yaml

feat: add localization config modal

---

.changeset/rude-lamps-warn.md
packages/root-cms/ui/components/DocActionsMenu/DocActionsMenu.tsx
packages/root-cms/ui/components/VersionHistoryModal/VersionHistoryModal.css
packages/root-cms/ui/components/VersionHistoryModal/VersionHistoryModal.tsx
packages/root-cms/ui/ui.tsx
packages/root-cms/ui/utils/doc.ts

feat: add ui for listing and restoring versions

---

.changeset/brown-cups-hug.md
docs/routes/guide/project-structure.tsx
examples/basepath/layouts/BaseLayout.tsx
examples/basepath/package.json
examples/basepath/root.config.ts
examples/basepath/routes/bar.tsx
examples/basepath/routes/index.tsx
examples/basepath/tsconfig.json
examples/blog/root.config.ts
packages/root-cms/core/app.tsx
packages/root-cms/ui/components/SlugInput/SlugInput.tsx
packages/root-cms/ui/pages/CollectionPage/CollectionPage.tsx
packages/root-cms/ui/pages/DocumentPage/DocumentPage.tsx
packages/root-cms/ui/ui.tsx
packages/root-cms/ui/utils/doc-urls.ts
packages/root/src/cli/commands/dev.ts
packages/root/src/core/config.ts
packages/root/src/render/router.ts
packages/root/test/fixtures/i18n-url-format/root.config.ts

feat: add `basePath` config

---

.changeset/fast-carpets-begin.md
packages/root-cms/ui/components/LocalizationModal/LocalizationModal.tsx
packages/root-cms/ui/components/RichTextEditor/RichTextEditor.tsx
packages/root-cms/ui/pages/TranslationsArbPage/TranslationsArbPage.css
packages/root-cms/ui/pages/TranslationsArbPage/TranslationsArbPage.tsx
packages/root-cms/ui/pages/TranslationsPage/TranslationsPage.css
packages/root-cms/ui/pages/TranslationsPage/TranslationsPage.tsx
packages/root-cms/ui/ui.tsx
packages/root-cms/ui/utils/arb.ts
packages/root-cms/ui/utils/doc.ts
packages/root-cms/ui/utils/extract.ts

feat: basic arb download ui

---

.changeset/friendly-parrots-look.md
packages/root-cms/ui/pages/TranslationsEditPage/TranslationsEditPage.css
packages/root-cms/ui/pages/TranslationsEditPage/TranslationsEditPage.tsx
packages/root-cms/ui/pages/TranslationsPage/TranslationsPage.css
packages/root-cms/ui/pages/TranslationsPage/TranslationsPage.tsx
packages/root-cms/ui/ui.tsx
packages/root-cms/ui/utils/l10n.ts

feat: add edit translations page

---

.changeset/spicy-ducks-stare.md
packages/root-cms/core/app.tsx
packages/root-cms/ui/components/AssetUploader/AssetUploader.tsx
packages/root-cms/ui/pages/AssetsPage/AssetsPage.tsx

chore: add favicon to root cms

---

examples/blog/layouts/BaseLayout.tsx
examples/blog/root.config.ts
packages/root-cms/core/app.tsx
packages/root-password-protect/core/password-page.tsx
packages/root/src/core/config.ts
packages/root/src/core/hooks/useRequestContext.ts
packages/root/src/render/render.tsx

feat: add server csp config options

---

.changeset/shy-cars-argue.md
.gitignore
examples/blog/package.json
packages/root/src/cli/cli.ts
packages/root/src/cli/create-package.ts
packages/root/src/utils/fsutils.ts

feat: add `root create-package` cli command

---

.changeset/slimy-flies-hear.md
packages/root-cms/cli/generate-types.ts
packages/root-cms/core/plugin.ts
packages/root/src/cli/dev.ts
packages/root/src/core/plugin.ts

feat: auto generate .d.ts types when .schema.ts files change

---

.changeset/proud-mangos-give.md
packages/root/bin/root.js
packages/root/package.json
pnpm-lock.yaml

fix: fix sourcemaps in render-time errors

---

packages/root-cms/core/schema.ts
packages/root-cms/ui/components/DocEditor/DocEditor.tsx

feat: add hideLabel to schema fields

---

.changeset/hip-crabs-fail.md
docs/root.config.ts
packages/root-cms/core/app.tsx
packages/root-cms/core/plugin.ts
packages/root-cms/ui/layout/Layout.css
packages/root-cms/ui/layout/Layout.tsx
packages/root-cms/ui/pages/SidebarToolsPage/SidebarToolsPage.css
packages/root-cms/ui/pages/SidebarToolsPage/SidebarToolsPage.tsx
packages/root-cms/ui/ui.tsx

feat: add custom cms sidebar tools

---

.changeset/lazy-suns-happen.md
packages/root-cms/ui/components/CopyDocModal/CopyDocModal.tsx
packages/root-cms/ui/utils/doc.ts

feat: add option to overwrite when copying doc

---

.changeset/spotty-buttons-leave.md
docs/package.json
packages/root/codegen/element/[name].ts.tpl
packages/root/src/cli/cli.ts
packages/root/src/cli/codegen.ts

feat: add codegen cli

---

.changeset/fresh-countries-brush.md
packages/root-cms/core/client.ts
packages/root-cms/ui/components/DocActionsMenu/DocActionsMenu.tsx
packages/root-cms/ui/components/DocEditor/DocEditor.tsx
packages/root-cms/ui/components/DocStatusBadges/DocStatusBadges.tsx
packages/root-cms/ui/components/LockPublishingModal/LockPublishingModal.css
packages/root-cms/ui/components/LockPublishingModal/LockPublishingModal.tsx
packages/root-cms/ui/ui.tsx
packages/root-cms/ui/utils/doc.ts
packages/root-cms/ui/utils/time.ts

feat: add publishing lock

---

.changeset/lemon-waves-tell.md
packages/root-cms/package.json
packages/root-cms/ui/components/DocDiffViewer/DocDiffViewer.css
packages/root-cms/ui/components/DocDiffViewer/DocDiffViewer.tsx
packages/root-cms/ui/components/PublishDocModal/PublishDocModal.css
packages/root-cms/ui/components/PublishDocModal/PublishDocModal.tsx
packages/root-cms/ui/components/VersionHistoryModal/VersionHistoryModal.css
packages/root-cms/ui/components/VersionHistoryModal/VersionHistoryModal.tsx
packages/root-cms/ui/pages/ComparePage/ComparePage.css
packages/root-cms/ui/pages/ComparePage/ComparePage.tsx
packages/root-cms/ui/pages/DocumentPage/DocumentPage.css
packages/root-cms/ui/react-json-view-compare.d.ts
packages/root-cms/ui/ui.tsx
packages/root-cms/ui/utils/doc.ts
pnpm-lock.yaml

feat: add diff viewer to publishing flow

---

.changeset/brave-dots-walk.md
packages/root-cms/ui/components/DocEditor/DocEditor.css
packages/root-cms/ui/components/DocEditor/DocEditor.tsx
packages/root-cms/ui/pages/DocumentPage/DocumentPage.css

fix: update drawer to details based component

---

.changeset/tough-readers-walk.md
packages/root-cms/ui/components/DocEditor/DocEditor.css
packages/root-cms/ui/components/DocEditor/DocEditor.tsx
packages/root-cms/ui/components/EditTranslationsModal/EditTranslationsModal.css
packages/root-cms/ui/components/EditTranslationsModal/EditTranslationsModal.tsx
packages/root-cms/ui/components/ExportSheetModal/ExportSheetModal.tsx
packages/root-cms/ui/ui.tsx
packages/root-cms/ui/utils/doc.ts
packages/root-cms/ui/utils/extract.ts

feat: add show translations action icons to fields

---

.changeset/two-carpets-type.md
docs/root.config.ts
packages/root-cms/ui/components/EditTranslationsModal/EditTranslationsModal.css
packages/root-cms/ui/components/EditTranslationsModal/EditTranslationsModal.tsx
packages/root-cms/ui/components/LocalizationModal/LocalizationModal.css
packages/root-cms/ui/components/LocalizationModal/LocalizationModal.tsx
packages/root-cms/ui/pages/DocTranslationsPage/DocTranslationsPage.css
packages/root-cms/ui/pages/DocTranslationsPage/DocTranslationsPage.tsx
packages/root-cms/ui/ui.tsx
packages/root-cms/ui/utils/extract.ts

feat: add doc translations editor page

---

.changeset/forty-needles-lay.md
packages/root-cms/core/client.ts

feat: add getUserRole() to cms client

---

.changeset/four-items-film.md
packages/root-cms/ui/components/LocalizationModal/LocalizationModal.tsx

feat: use country display name for `ALL_xx` locales

---

.changeset/brave-kids-swim.md
packages/root-cms/ui/components/DocEditor/DocEditor.css
packages/root-cms/ui/components/DocEditor/fields/FileField.tsx
packages/root-cms/ui/styles/global.css
packages/root-cms/ui/utils/gcs.ts

feat: add video width/height to uploaded files

---

.changeset/kind-pans-check.md
.changeset/strong-planes-float.md
packages/root-cms/core/client.ts
packages/root-cms/core/compatibility.ts
packages/root-cms/core/plugin.ts
packages/root/src/core/config.ts

feat: [v2] add compatibility check for v2 translations

---

.changeset/silver-roses-turn.md
packages/root-cms/ui/components/DocEditor/fields/ReferenceField.tsx

fix: fix reference field when doc is deleted

---

.changeset/sweet-windows-cheat.md
packages/root/src/cli/build.ts
packages/root/test/sitemap.test.ts

fix: fix sitemap ordering

---

.changeset/silent-eyes-drop.md
packages/root-cms/core/client.ts

feat: add option for listing raw docs

---

.changeset/long-cups-search.md
packages/root-cms/ui/components/DocEditor/DocEditor.css
packages/root-cms/ui/components/DocEditor/fields/FileField.tsx
packages/root-cms/ui/utils/gcs.ts

feat: add alt text to video files

---

packages/root/src/cli/build.ts
packages/root/src/core/config.ts
packages/root/test/exclude-intl-default-locale.test.ts
packages/root/test/fixtures/exclude-intl-default-locale/root.config.ts
packages/root/test/fixtures/exclude-intl-default-locale/routes/foo/[slug].tsx
packages/root/test/fixtures/exclude-intl-default-locale/routes/index.tsx
packages/root/test/fixtures/exclude-intl-default-locale/translations/fr.json

feat: add excludeDefaultLocaleFromIntlPaths build option

---

.changeset/grumpy-dogs-cross.md
packages/root-cms/ui/components/DocEditor/DocEditor.tsx
packages/root-cms/ui/components/DocEditor/fields/NumberField.tsx

feat: add NumberField

---

.changeset/young-pears-refuse.md
packages/root-cms/ui/components/RichTextEditor/RichTextEditor.tsx

fix: fix richtext editor destroy error

---

.changeset/eight-avocados-matter.md
packages/root/src/core/core.ts
packages/root/src/core/hooks/useTranslations.ts
packages/root/src/core/hooks/useTranslationsMiddleware.tsx
packages/root/test/fixtures/translation-middleware/root.config.ts
packages/root/test/fixtures/translation-middleware/routes/index.tsx
packages/root/test/translation-middleware.test.ts

- add TranslationMiddlewareProvider and hook
- wire up useTranslations to run middleware pre/post transforms
- export middleware from core
- test translation middleware functionality
- `pnpm --filter @blinkk/root test` *(fails: Connect Timeout Error)*

Add translation middleware for useTranslations

---

packages/root/src/core/config.ts
packages/root/src/middleware/redirects.ts

i keep forgetting the syntax. is this right?

document the `RootRedirectConfig` interface

---

.changeset/tricky-hotels-doubt.md
packages/root-cms/ui/components/FileUploadField/FileUploadField.css
packages/root-cms/ui/components/FileUploadField/FileUploadField.tsx

- also refactors the upload button to use the mantine button
fixes #649

fix: enable dropping over the file upload button

---

.changeset/six-radios-cover.md
packages/root-cms/package.json
packages/root-cms/ui/components/AiEditModal/AiEditModal.css
packages/root-cms/ui/components/AiEditModal/AiEditModal.tsx
packages/root-cms/ui/components/JsDiff/JsDiff.css
packages/root-cms/ui/components/JsDiff/JsDiff.tsx
packages/root-cms/ui/pages/AIPage/AIPage.tsx
pnpm-lock.yaml

feat: improve usability of ai diff flow

---

.changeset/friendly-games-wonder.md
packages/root-cms/ui/pages/DocumentPage/DocumentPage.css
packages/root-cms/ui/pages/DocumentPage/DocumentPage.tsx

https://github.com/user-attachments/assets/5d2cec59-0121-47aa-a47a-e17f29224147

fix: resize iframe when window resizes

---

packages/root-cms/ui/hooks/useDraft.ts

Prior to this change, the db watcher would stop as soon as the browser tab loses focus, and when re-activating the tab, a loading spinner would appear while the db watcher starts up again. So when copying/pasting content from another tab, this is incredibly slow/painful.
In this change, a 30s timeout is added before the db watcher is stopped.

fix: add visibility timeout for db watcher

---

packages/root-cms/ui/components/AiEditModal/AiEditModal.tsx
packages/root-cms/ui/components/ChatBar/ChatBar.tsx

fix: handle missing data from ai.chat endpoint
